### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by paviro** [volumio/volumio-plugins#17]
Is there any documentation available? How would I for example execute a function whenever audio starts and stops to play?

**Comment by balbuze** [comment]
Now, have a look here  : https://volumio.github.io/docs/Plugin_System/Plugin_System_Overview.html

**Comment by paviro** [comment]
I tried writing one but I always get `The folowing error occurred when installing the plugin: TypeError: Cannot read property 'name' of undefined` even when installing the official spotify plugin.

**Comment by buguibu** [comment]
I faced the same error and my problems were: 

- i was making the *.zip* of the folder instead of all the files and folder
- do not forget to add the _node_modules_ folder to the plugin zip
- as said in [The plugins.json file](https://volumio.github.io/docs/Plugin_System/Plugin_System_Overview.html) i forgot to add my plugin to _/data/plugins/plugins.json_
