### ISSUE TITLE
Feature Request : Touchscreen locking

### ISSUE THREAD

**Issue by rshamsnejad** [volumio/volumio-plugins#448]
Hi ! Thanks for the touchscreen plugin, it works great on my Pi3B+/Official 7" setup.

I'm planning on using Volumio with touchscreen to make an ambient music player, and I would find very useful in this situation to have a screen locking feature on the "now playing" menu, with a slider to unlock. It could be triggered either automatically through an idle timeout, or manually with a lock icon.

What do you think ?

**Comment by gvolt** [comment]
Hi @rshamsnejad, thanks for your feedback!

The way I see it, the screen locking feature you describe needs a modification of Volumio's UI. The touch display plugin just presents the Volumio Web UI in a local browser. The plugin acts like a client and does not (and should not) modify the UI. UI related files are part of the system integrity check and manipulating those files would break the update function of the system.

That's why the feature would have to be implemented server-side imho. So I suggest to request the screen locking function in the [Volumio](https://github.com/volumio/Volumio2) or [Volumio UI](https://github.com/volumio/Volumio) repo.

**Comment by rshamsnejad** [comment]
Well noted, @gvolt, i'll repost this in Volumio-UI. Thanks !
